repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer          # ğŸ”š ajoute une ligne vide Ã  la fin de chaque fichier (bonne pratique UNIX)
      - id: trailing-whitespace        # ğŸ§½ supprime les espaces inutiles en fin de ligne
      - id: check-yaml                 # âœ… vÃ©rifie que les fichiers YAML sont valides
      - id: check-added-large-files    # ğŸš« empÃªche de commit des fichiers trop gros (ex: CSV, modÃ¨les...)


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff                       # ğŸ•µï¸â€â™€ï¸ dÃ©tecte les erreurs, problÃ¨mes de style et bonnes pratiques
      - id: ruff-format                # ğŸ§¹ reformate automatiquement le code (Ã©quiv. Ã  black/isort)
